import type { DocumentModel } from '@/services/contracts'
import type { Lang } from '@/i18n'
import { formatDate, formatDateTime, formatTime } from '@/fixtures/calendar'
import { translate } from '@/i18n'
import { statusKey } from '@/i18n'

/**
 * Turns a document model into a self-contained page: the same HTML is shown
 * in the console, saved as a file and sent to the printer, so what the
 * presenter sees is byte-for-byte what the customer would receive.
 *
 * Layout follows the paper each system prints: an order confirmation with
 * sold-to / ship-to / shipping point blocks and one line item; a bill of
 * lading with the weigh-scale ticket and three signature lines; the signed
 * copy with the receiver's block filled and the milestones; a delivery
 * record; a tax invoice built from the signed bill of lading.
 */

const L = {
  en: {
    orderConfirmation: 'Order confirmation', bol: 'Bill of lading', signedBol: 'Bill of lading — signed copy', deliveryRecord: 'Delivery record', invoice: 'Tax invoice',
    number: 'Number', date: 'Date', issuedBy: 'Issued by', page: 'Page 1 of 1',
    orderNo: 'Sales order', consoleRef: 'Console reference', requestRef: 'Order request', customerPo: 'Customer PO', owner: 'Service desk owner', priority: 'Priority',
    soldTo: 'Sold-to', shipTo: 'Ship-to', shippingPoint: 'Shipping point', account: 'Account', contact: 'Contact', site: 'Site code',
    window: 'Delivery window', incoterms: 'Delivery terms', paymentTerms: 'Payment terms', createdAt: 'Created',
    item: 'Item', material: 'Material', description: 'Description', quantity: 'Quantity', unit: 'Unit', unitPrice: 'Unit price', amount: 'Amount',
    subtotal: 'Subtotal', taxesAtInvoice: 'Taxes are applied on the invoice issued after delivery.', total: 'Total', currency: 'CAD', due: 'Due',
    carrier: 'Carrier', truck: 'Truck', driver: 'Driver', freight: 'Freight (carrier rate)', perTonne: 'per tonne', connected: 'Connected carrier system', portal: 'Carrier portal',
    scaleTicket: 'Scale ticket', gross: 'Gross', tare: 'Tare', net: 'Net', seal: 'Seal', loadedAt: 'Loaded', bay: 'Bay', operator: 'Scale operator',
    hazard: 'Hazard class', notRegulated: 'Not regulated — bulk cement, non-hazardous', instructions: 'Delivery instructions',
    unloadNote: (m: number) => `Receiver unloads; allow ${m} minutes on site. Pneumatic discharge into customer silo.`,
    loader: 'Loaded by', driverSig: 'Driver', receiver: 'Received by', signature: 'Signature', name: 'Name', time: 'Time', toBeSigned: 'to be signed on delivery',
    signedOnDevice: 'Signed on the carrier device', uploadedFile: 'Uploaded from the carrier system', archived: 'Archived',
    milestones: 'Milestones', status: 'Status', recordedBy: 'Recorded by', source: 'Source',
    delivered: 'Delivered', onTime: 'On time', yes: 'Yes', no: 'No', late: 'Late', cycle: 'Order to delivery', hours: 'h', problems: 'Problems reported', noProblems: 'No problems reported at delivery.',
    references: 'Related documents', annotations: 'Notes',
    billTo: 'Bill to', invoiceNo: 'Invoice', deliveryDate: 'Delivery date', bolRef: 'Bill of lading', remitTo: 'Remit to', paymentNote: (d: string) => `Payable within 30 days. Due ${d}.`,
    issuedFrom: 'Issued from the signed bill of lading', deliveryIncluded: 'Delivery included (DAP)',
    footer: 'Synthetic demo document generated by the order console from the order record and its events. Not a real transaction.',
    tonnes: 't', line: 'Line', qty: (t: number) => `${t.toLocaleString('en-CA')} t`,
    sourceOf: { erp: 'System of record', console: 'Order console', carrier: 'Carrier', scale: 'Weigh scale', customer: 'Customer', system: 'Automatic' } as Record<string, string>,
    priorityOf: { standard: 'Standard', priority: 'Priority', urgent: 'Urgent' } as Record<string, string>,
    deviation: { wrong_product: 'Wrong product', short_quantity: 'Less than ordered', excess_quantity: 'More than ordered', handover_issue: 'Handover problem' } as Record<string, string>,
  },
  fr: {
    orderConfirmation: 'Confirmation de commande', bol: 'Connaissement', signedBol: 'Connaissement — copie signée', deliveryRecord: 'Relevé de livraison', invoice: 'Facture',
    number: 'Numéro', date: 'Date', issuedBy: 'Émis par', page: 'Page 1 de 1',
    orderNo: 'Commande de vente', consoleRef: 'Référence console', requestRef: 'Demande de commande', customerPo: 'Bon de commande client', owner: 'Responsable au service client', priority: 'Priorité',
    soldTo: 'Donneur d’ordre', shipTo: 'Livré à', shippingPoint: 'Point d’expédition', account: 'Compte', contact: 'Contact', site: 'Code du site',
    window: 'Fenêtre de livraison', incoterms: 'Conditions de livraison', paymentTerms: 'Conditions de paiement', createdAt: 'Créée',
    item: 'Poste', material: 'Article', description: 'Désignation', quantity: 'Quantité', unit: 'Unité', unitPrice: 'Prix unitaire', amount: 'Montant',
    subtotal: 'Sous-total', taxesAtInvoice: 'Les taxes sont appliquées sur la facture émise après la livraison.', total: 'Total', currency: 'CAD', due: 'Échéance',
    carrier: 'Transporteur', truck: 'Camion', driver: 'Chauffeur', freight: 'Transport (tarif transporteur)', perTonne: 'la tonne', connected: 'Système transporteur connecté', portal: 'Portail transporteur',
    scaleTicket: 'Ticket de pesée', gross: 'Brut', tare: 'Tare', net: 'Net', seal: 'Scellé', loadedAt: 'Chargé', bay: 'Quai', operator: 'Opérateur de bascule',
    hazard: 'Classe de danger', notRegulated: 'Non réglementé — ciment en vrac, non dangereux', instructions: 'Instructions de livraison',
    unloadNote: (m: number) => `Déchargement par le destinataire ; prévoir ${m} minutes sur place. Déchargement pneumatique dans le silo du client.`,
    loader: 'Chargé par', driverSig: 'Chauffeur', receiver: 'Reçu par', signature: 'Signature', name: 'Nom', time: 'Heure', toBeSigned: 'à signer à la livraison',
    signedOnDevice: 'Signé sur l’appareil du transporteur', uploadedFile: 'Téléversé depuis le système du transporteur', archived: 'Archivé',
    milestones: 'Étapes', status: 'Statut', recordedBy: 'Enregistré par', source: 'Source',
    delivered: 'Livrée', onTime: 'À l’heure', yes: 'Oui', no: 'Non', late: 'En retard', cycle: 'De la commande à la livraison', hours: 'h', problems: 'Problèmes signalés', noProblems: 'Aucun problème signalé à la livraison.',
    references: 'Documents liés', annotations: 'Notes',
    billTo: 'Facturer à', invoiceNo: 'Facture', deliveryDate: 'Date de livraison', bolRef: 'Connaissement', remitTo: 'Paiement à', paymentNote: (d: string) => `Payable sous 30 jours. Échéance le ${d}.`,
    issuedFrom: 'Émise à partir du connaissement signé', deliveryIncluded: 'Livraison incluse (DAP)',
    footer: 'Document de démonstration synthétique généré par la console à partir de la commande et de ses événements. Pas une transaction réelle.',
    tonnes: 't', line: 'Ligne', qty: (t: number) => `${t.toLocaleString('fr-CA')} t`,
    sourceOf: { erp: 'Système de référence', console: 'Console des commandes', carrier: 'Transporteur', scale: 'Bascule', customer: 'Client', system: 'Automatique' } as Record<string, string>,
    priorityOf: { standard: 'Standard', priority: 'Prioritaire', urgent: 'Urgente' } as Record<string, string>,
    deviation: { wrong_product: 'Mauvais produit', short_quantity: 'Moins que commandé', excess_quantity: 'Plus que commandé', handover_issue: 'Problème de remise' } as Record<string, string>,
  },
} as const

type Dict = (typeof L)['en'] | (typeof L)['fr']

const CSS = `
  @page { size: A4; margin: 16mm; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #e9edf3; font-family: Inter, -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; color: #0b1220; font-size: 12px; line-height: 1.45; }
  .sheet { background: #fff; max-width: 820px; margin: 24px auto; padding: 44px 48px 36px; box-shadow: 0 8px 30px rgba(1,30,106,.12); }
  @media print { body { background: #fff; } .sheet { box-shadow: none; margin: 0; padding: 0; max-width: none; } }
  .head { display: flex; justify-content: space-between; gap: 24px; border-bottom: 2px solid #011e6a; padding-bottom: 14px; }
  .brand { font-size: 17px; font-weight: 700; letter-spacing: -.01em; color: #011e6a; }
  .brand small { display: block; font-size: 11px; font-weight: 500; color: #4b5563; margin-top: 3px; }
  .doc { text-align: right; }
  .doc h1 { margin: 0; font-size: 20px; letter-spacing: -.01em; color: #011e6a; }
  .doc .no { font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 15px; font-weight: 600; margin-top: 4px; }
  .doc .meta { color: #4b5563; font-size: 11px; margin-top: 2px; }
  .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-top: 18px; }
  .grid.two { grid-template-columns: repeat(2, 1fr); }
  .block { border: 1px solid #d5dbe5; border-radius: 6px; padding: 10px 12px; min-height: 92px; }
  .block h3 { margin: 0 0 6px; font-size: 10px; letter-spacing: .12em; text-transform: uppercase; color: #6b7280; font-weight: 600; }
  .block b { display: block; font-size: 12.5px; }
  .block .sub { color: #4b5563; font-size: 11.5px; }
  .kv { display: grid; grid-template-columns: 1fr 1fr; gap: 6px 18px; margin-top: 16px; font-size: 11.5px; }
  .kv div { display: flex; justify-content: space-between; gap: 12px; border-bottom: 1px dotted #d5dbe5; padding: 3px 0; }
  .kv span:first-child { color: #6b7280; }
  .kv span:last-child { font-weight: 500; text-align: right; }
  table { width: 100%; border-collapse: collapse; margin-top: 18px; font-size: 11.5px; }
  th { text-align: left; font-size: 10px; letter-spacing: .1em; text-transform: uppercase; color: #6b7280; border-bottom: 1px solid #011e6a; padding: 6px 8px; }
  td { padding: 7px 8px; border-bottom: 1px solid #e5e9f0; vertical-align: top; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  .mono { font-family: "SF Mono", Menlo, Consolas, monospace; }
  .totals { margin-left: auto; width: 320px; margin-top: 10px; font-size: 12px; }
  .totals div { display: flex; justify-content: space-between; padding: 4px 8px; }
  .totals .grand { border-top: 2px solid #011e6a; font-weight: 700; font-size: 14px; margin-top: 4px; padding-top: 8px; }
  .note { margin-top: 14px; padding: 10px 12px; background: #eef7ff; border-left: 3px solid #1963ff; border-radius: 4px; font-size: 11.5px; }
  .sigs { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-top: 26px; }
  .sig { border-top: 1px solid #0b1220; padding-top: 6px; font-size: 11px; min-height: 64px; }
  .sig h4 { margin: 0; font-size: 10px; letter-spacing: .12em; text-transform: uppercase; color: #6b7280; font-weight: 600; }
  .sig .who { font-weight: 600; margin-top: 2px; }
  .sig .when { color: #4b5563; }
  .sig img { display: block; height: 52px; margin: 2px 0 2px -4px; }
  .sig .pending { color: #9ca3af; font-style: italic; margin-top: 10px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 10.5px; font-weight: 600; }
  .badge.ok { background: #e8f6ee; color: #146c43; }
  .badge.late { background: #fdecec; color: #b42318; }
  .foot { margin-top: 30px; border-top: 1px solid #d5dbe5; padding-top: 10px; display: flex; justify-content: space-between; gap: 16px; color: #6b7280; font-size: 10px; }
  h2 { font-size: 11px; letter-spacing: .12em; text-transform: uppercase; color: #011e6a; margin: 22px 0 0; }
`

const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string)
const money = (n: number, lang: Lang) => n.toLocaleString(lang === 'fr' ? 'fr-CA' : 'en-CA', { style: 'currency', currency: 'CAD' })
const num = (n: number, lang: Lang, digits = 2) => n.toLocaleString(lang === 'fr' ? 'fr-CA' : 'en-CA', { minimumFractionDigits: digits, maximumFractionDigits: digits })

function head(m: DocumentModel, title: string, number: string, d: Dict, lang: Lang, extra = ''): string {
  return `<div class="head">
    <div class="brand">${esc(m.seller.name)}<small>${esc(m.seller.address)}<br>${esc(m.seller.taxNo)}</small></div>
    <div class="doc"><h1>${esc(title)}</h1><div class="no">${esc(number)}</div><div class="meta">${d.date}: ${esc(formatDateTime(m.issuedAt, lang))}${extra ? ' · ' + esc(extra) : ''}</div><div class="meta">${d.issuedBy}: ${esc(m.source)} · ${d.page}</div></div>
  </div>`
}

function party(title: string, lines: (string | null | undefined)[], sub?: string): string {
  const [first, ...rest] = lines.filter(Boolean) as string[]
  return `<div class="block"><h3>${esc(title)}</h3><b>${esc(first ?? '')}</b>${rest.map((r) => `<div class="sub">${esc(r)}</div>`).join('')}${sub ? `<div class="sub">${esc(sub)}</div>` : ''}</div>`
}

function kv(rows: [string, string][]): string {
  return `<div class="kv">${rows.map(([k, v]) => `<div><span>${esc(k)}</span><span>${esc(v)}</span></div>`).join('')}</div>`
}

function windowText(m: DocumentModel, lang: Lang): string {
  return `${formatDate(m.order.windowStart, lang)} ${formatTime(m.order.windowStart)}–${formatTime(m.order.windowEnd)}`
}

function lineTable(m: DocumentModel, d: Dict, lang: Lang, withPrice: boolean): string {
  return `<table><thead><tr><th>${d.item}</th><th>${d.material}</th><th>${d.description}</th><th class="num">${d.quantity}</th>${withPrice ? `<th class="num">${d.unitPrice}</th><th class="num">${d.amount}</th>` : ''}</tr></thead>
  <tbody><tr><td>10</td><td class="mono">${esc(m.line.material)}</td><td>${esc(m.line.description)}</td><td class="num">${d.qty(m.line.tonnes)}</td>${withPrice ? `<td class="num">${money(m.line.unitPrice, lang)} / ${d.tonnes}</td><td class="num">${money(m.line.amount, lang)}</td>` : ''}</tr></tbody></table>`
}

function milestones(m: DocumentModel, d: Dict, lang: Lang): string {
  return `<h2>${d.milestones}</h2><table><thead><tr><th>${d.time}</th><th>${d.status}</th><th>${d.recordedBy}</th><th>${d.source}</th></tr></thead><tbody>
  ${m.events.map((e) => `<tr><td class="mono">${esc(formatDateTime(e.at, lang))}</td><td>${esc(translate(lang, statusKey(e.status)))}</td><td>${esc(e.actor)}</td><td>${esc(d.sourceOf[e.source] ?? e.source)}</td></tr>`).join('')}
  </tbody></table>`
}

function carrierBlock(m: DocumentModel, d: Dict): string {
  const c = m.carrier
  return party(d.carrier, c ? [c.name, `SCAC ${c.scac} · ${c.connected ? d.connected : d.portal}`, `${d.truck} ${c.truckPlate} · ${d.driver} ${c.driver}`] : ['—'])
}

function bolBody(m: DocumentModel, d: Dict, lang: Lang, signed: boolean): string {
  const s = m.scale
  const pod = m.pod
  return `
  <div class="grid">
    ${party(d.shippingPoint, [m.terminal.name, m.terminal.address], `${d.site} ${m.terminal.siteCode}`)}
    ${party(d.shipTo, [m.shipTo.name, m.shipTo.address], `${d.contact}: ${m.customer.contact}`)}
    ${carrierBlock(m, d)}
  </div>
  ${kv([[d.orderNo, m.order.erpRef], [d.customerPo, m.order.customerPo], [d.soldTo, `${m.customer.name} · ${m.customer.accountNo}`], [d.window, windowText(m, lang)], [d.loadedAt, s ? formatDateTime(s.loadedAt, lang) : '—'], [d.bay, s ? String(s.bay) : '—']])}
  ${lineTable(m, d, lang, false)}
  <h2>${d.scaleTicket}</h2>
  <table><thead><tr><th>${d.scaleTicket}</th><th class="num">${d.gross}</th><th class="num">${d.tare}</th><th class="num">${d.net}</th><th>${d.seal}</th><th>${d.operator}</th></tr></thead>
  <tbody><tr><td class="mono">${esc(s?.ticket ?? '—')}</td><td class="num">${s ? num(s.gross, lang, 2) + ' t' : '—'}</td><td class="num">${s ? num(s.tare, lang, 2) + ' t' : '—'}</td><td class="num"><b>${s ? num(s.net, lang, 2) + ' t' : '—'}</b></td><td class="mono">${esc(s?.seal ?? '—')}</td><td>${esc(s?.operator ?? '—')}</td></tr></tbody></table>
  ${kv([[d.hazard, d.notRegulated], [d.incoterms, m.order.incoterms]])}
  <div class="note"><b>${d.instructions}.</b> ${d.unloadNote(m.shipTo.unloadMinutes)}</div>
  <div class="sigs">
    <div class="sig"><h4>${d.loader}</h4><div class="who">${esc(s?.operator ?? '—')}</div><div class="when">${s ? esc(formatDateTime(s.loadedAt, lang)) : ''}</div></div>
    <div class="sig"><h4>${d.driverSig}</h4><div class="who">${esc(m.carrier?.driver ?? '—')}</div><div class="when">${s ? esc(formatTime(s.loadedAt)) : ''} · ${esc(m.carrier?.truckPlate ?? '')}</div></div>
    <div class="sig"><h4>${d.receiver}</h4>${signed && pod
      ? `${pod.signaturePng ? `<img src="${pod.signaturePng}" alt="${d.signature}">` : `<div class="when">${pod.fileName ? `${d.uploadedFile} · ${esc(pod.fileName)}` : d.signedOnDevice}</div>`}<div class="who">${esc(pod.signedBy)}</div><div class="when">${esc(formatDateTime(pod.signedAt, lang))}</div>`
      : `<div class="pending">${d.toBeSigned}</div>`}</div>
  </div>
  ${signed && pod ? `${milestones(m, d, lang)}${pod.annotations.length ? `<h2>${d.annotations}</h2><table><tbody>${pod.annotations.map((a) => `<tr><td class="mono">${esc(formatDateTime(a.at, lang))}</td><td>${esc(a.by)}</td><td>${esc(a.text)}</td></tr>`).join('')}</tbody></table>` : ''}` : ''}`
}

export function documentHtml(m: DocumentModel, lang: Lang): string {
  const d: Dict = L[lang]
  let title = ''
  let body = ''
  let extra = ''
  switch (m.kind) {
    case 'erp_order': {
      title = d.orderConfirmation
      body = `
      <div class="grid">
        ${party(d.soldTo, [m.customer.name, m.customer.address], `${d.account} ${m.customer.accountNo} · ${d.contact}: ${m.customer.contact}`)}
        ${party(d.shipTo, [m.shipTo.name, m.shipTo.address], `${m.shipTo.id}`)}
        ${party(d.shippingPoint, [m.terminal.name, m.terminal.address], `${d.site} ${m.terminal.siteCode}`)}
      </div>
      ${kv([[d.createdAt, formatDateTime(m.order.createdAt, lang)], [d.requestRef, m.order.requestRef], [d.customerPo, m.order.customerPo], [d.consoleRef, m.order.consoleId], [d.window, windowText(m, lang)], [d.priority, d.priorityOf[m.order.priority]], [d.incoterms, m.order.incoterms], [d.paymentTerms, m.order.paymentTerms], [d.owner, m.order.owner], [d.carrier, m.carrier ? `${m.carrier.name} · ${money(m.carrier.ratePerTonne, lang)} ${d.perTonne}` : '—']])}
      ${lineTable(m, d, lang, true)}
      <div class="totals"><div><span>${d.subtotal}</span><span>${money(m.line.amount, lang)}</span></div>${m.carrier ? `<div><span>${d.freight}</span><span>${money(m.carrier.freightAmount, lang)}</span></div>` : ''}<div class="grand"><span>${d.total} (${d.currency})</span><span>${money(m.line.amount + (m.carrier?.freightAmount ?? 0), lang)}</span></div></div>
      <div class="note">${d.taxesAtInvoice}</div>`
      break
    }
    case 'bol': {
      title = d.bol
      extra = m.scale ? `${d.scaleTicket} ${m.scale.ticket}` : ''
      body = bolBody(m, d, lang, false)
      break
    }
    case 'signed_bol': {
      title = d.signedBol
      extra = m.pod?.archivedAt ? `${d.archived} ${formatDateTime(m.pod.archivedAt, lang)}` : ''
      body = bolBody(m, d, lang, true)
      break
    }
    case 'delivery_record': {
      title = d.deliveryRecord
      const dl = m.delivery
      body = `
      <div class="grid">
        ${party(d.soldTo, [m.customer.name, m.customer.address], `${d.account} ${m.customer.accountNo}`)}
        ${party(d.shipTo, [m.shipTo.name, m.shipTo.address])}
        ${carrierBlock(m, d)}
      </div>
      ${kv([[d.orderNo, m.order.erpRef], [d.customerPo, m.order.customerPo], [d.window, windowText(m, lang)], [d.delivered, dl ? formatDateTime(dl.deliveredAt, lang) : '—'], [d.cycle, dl?.cycleHours != null ? `${num(dl.cycleHours, lang, 1)} ${d.hours}` : '—'], [d.owner, m.order.owner]])}
      <p style="margin:14px 0 0">${d.onTime}: <span class="badge ${dl?.onTime ? 'ok' : 'late'}">${dl?.onTime ? d.yes : d.late}</span></p>
      ${lineTable(m, d, lang, false)}
      ${milestones(m, d, lang)}
      <h2>${d.problems}</h2>
      ${m.deviations.length ? `<table><tbody>${m.deviations.map((dv) => `<tr><td class="mono">${esc(formatDateTime(dv.filedAt, lang))}</td><td>${esc(d.deviation[dv.kind] ?? dv.kind)}${dv.qtyDelta ? ` (${dv.qtyDelta > 0 ? '+' : ''}${dv.qtyDelta} t)` : ''}</td><td>${esc(dv.note)}</td><td>${esc(dv.filedBy)}</td><td>${esc(dv.state)}</td></tr>`).join('')}</tbody></table>` : `<p class="sub" style="color:#4b5563">${d.noProblems}</p>`}
      ${kv([[d.bolRef, m.scale ? `BOL-${m.order.erpRef.slice(-5)} · ${m.scale.ticket}` : '—'], [d.invoiceNo, m.invoice?.number ?? '—']])}`
      break
    }
    case 'invoice': {
      title = d.invoice
      const inv = m.invoice
      body = `
      <div class="grid">
        ${party(d.billTo, [m.customer.name, m.customer.address], `${d.account} ${m.customer.accountNo} · ${d.contact}: ${m.customer.contact}`)}
        ${party(d.shipTo, [m.shipTo.name, m.shipTo.address])}
        ${party(d.remitTo, [m.seller.name, m.seller.address], m.seller.taxNo)}
      </div>
      ${kv([[d.orderNo, m.order.erpRef], [d.customerPo, m.order.customerPo], [d.bolRef, `BOL-${m.order.erpRef.slice(-5)}`], [d.deliveryDate, m.delivery ? formatDateTime(m.delivery.deliveredAt, lang) : '—'], [d.paymentTerms, m.order.paymentTerms], [d.due, inv ? formatDate(inv.due, lang) : '—']])}
      ${lineTable(m, d, lang, true)}
      <div class="totals"><div><span>${d.subtotal}</span><span>${money(inv?.subtotal ?? m.line.amount, lang)}</span></div><div><span>${d.deliveryIncluded}</span><span>${money(0, lang)}</span></div>${(inv?.taxes ?? []).map((tx) => `<div><span>${esc(tx.label)}</span><span>${money(tx.amount, lang)}</span></div>`).join('')}<div class="grand"><span>${d.total} (${d.currency})</span><span>${money(inv?.total ?? m.line.amount, lang)}</span></div></div>
      <div class="note">${inv ? d.paymentNote(formatDate(inv.due, lang)) : ''} ${d.issuedFrom}.</div>`
      break
    }
  }
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><title>${esc(title)} ${esc(m.reference)}</title><style>${CSS}</style></head><body><div class="sheet">${head(m, title, m.reference, d, lang, extra)}${body}<div class="foot"><span>${esc(m.seller.console)} · ${esc(m.order.consoleId)}</span><span>${d.footer}</span></div></div></body></html>`
}

export function documentFilename(m: DocumentModel): string {
  return `${m.reference}-${m.kind.replace(/_/g, '-')}.html`
}
